[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pisces-lite"
version = "2.0.0"
description = "ML-backend-agnostic core supporting data set discovery, loading, common spectrogram/PSD-based processing, and CV scoring."
requires-python = ">=3.12"
dependencies = [
    "senpy @ git+https://github.com/Arcascope/sensor_preprocessing_cpp.git@3.1.0#subdirectory=senpy",
    "matplotlib",
    "numpy",
    "scipy",
    "scikit-learn",
    "pandas",
    "seaborn",
    "tqdm",
]

[project.optional-dependencies]
dev = ["pytest"]
jax = [
    "jax-finufft>=1.3.0",
    "senpy[jax] @ git+https://github.com/Arcascope/sensor_preprocessing_cpp.git@3.1.0#subdirectory=senpy",
]

[tool.setuptools.packages.find]
where = ["src"]
